### ISSUE TITLE
what's the paper

### ISSUE THREAD

**Issue by QaQaaa-zzz** [niksknocksu/Decentralized_KalmanFilter#1]
i'd like to read the paper to understand the code well

**Comment by Zihao-HEU** [comment]
me too, what's the paper? I can't find the information of the paper in the code...

**Comment by niksknocksu** [comment]
"Stability of consensus extended Kalman filter for distributed state estimation"

**Comment by Zihao-HEU** [comment]
Thank you for your reply. This time I could read the paper and code.
